[versions]
agp = "8.11.1"
kotlin = "1.9.20"
webrtc = "1.0.32006"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
webrtc = { module = "org.webrtc:google-webrtc", version.ref = "webrtc" }
